opds_catalog/urls.py
from django.urls import path, re_path
from opds_catalog import feeds, dl

app_name = 'opds_catalog'

urlpatterns = [
    path('catalogs/', feeds.CatalogsFeed(), name='catalogs'),
    re_path(r'^catalogs/(?P<cat_id>[0-9]+)/$', feeds.CatalogsFeed(), name='cat_tree'),
    re_path(r'^catalogs/(?P<cat_id>[0-9]+)/(?P<page>[0-9]+)/$', feeds.CatalogsFeed(), name='cat_page'),

    path('books/', feeds.LangFeed(), name='lang_books'),
    path('books/0/', feeds.BooksFeed(), name='nolang_books'),
    re_path(r'^books/(?P<lang_code>[0-9])/$', feeds.BooksFeed(), name='char_books'),
    re_path(r'^books/(?P<lang_code>[0-9])/(?P<chars>.+)/$', feeds.BooksFeed(), name='chars_books'),

    path('authors/', feeds.LangFeed(), name='lang_authors'),
    path('authors/0/', feeds.AuthorsFeed(), name='nolang_authors'),
    re_path(r'^authors/(?P<lang_code>[0-9])/$', feeds.AuthorsFeed(), name='char_authors'),
    re_path(r'^authors/(?P<lang_code>[0-9])/(?P<chars>.+)/$', feeds.AuthorsFeed(), name='chars_authors'),

    path('series/', feeds.LangFeed(), name='lang_series'),
    path('series/0/', feeds.SeriesFeed(), name='nolang_series'),
    re_path(r'^series/(?P<lang_code>[0-9])/$', feeds.SeriesFeed(), name='char_series'),
    re_path(r'^series/(?P<lang_code>[0-9])/(?P<chars>.+)/$', feeds.SeriesFeed(), name='chars_series'),

    path('genres/', feeds.GenresFeed(), name='genres'),
    re_path(r'^genres/(?P<section>\d+)/$', feeds.GenresFeed(), name='genres'),

    path('search/', feeds.OpenSearch, name='opensearch'),
    # re_path(r'^search/{searchTerms}/$', feeds.OpenSearch, name='search_template'),

    re_path(r'^search/books/(?P<searchtype>[bmasgued])/(?P<searchterms>.+)/(?P<page>\d+)/$', feeds.SearchBooksFeed(), name='searchbooks'),
    re_path(r'^search/books/(?P<searchtype>[bmasgued])/(?P<searchterms>.+)/$', feeds.SearchBooksFeed(), name='searchbooks'),
    re_path(r'^search/books/(?P<searchtype>as)/(?P<searchterms>.+)/(?P<searchterms0>.+)/(?P<page>\d+)/$', feeds.SearchBooksFeed(), name='searchbooks'),
    re_path(r'^search/books/(?P<searchtype>as)/(?P<searchterms>.+)/(?P<searchterms0>.+)/$', feeds.SearchBooksFeed(), name='searchbooks'),
    re_path(r'^search/books/(?P<searchtype>as)/(?P<searchterms>.+)/$', feeds.SelectSeriesFeed(), name='searchbooks'),
    path('search/books/u/0/', feeds.SearchBooksFeed(), name='bookshelf'),

    re_path(r'^search/authors/(?P<searchtype>[bme])/(?P<searchterms>.+)/(?P<page>\d+)/$', feeds.SearchAuthorsFeed(), name='searchauthors'),
    re_path(r'^search/authors/(?P<searchtype>[bme])/(?P<searchterms>.+)/$', feeds.SearchAuthorsFeed(), name='searchauthors'),

    re_path(r'^search/series/(?P<searchtype>[bmae])/(?P<searchterms>.+)/(?P<page>\d+)/$', feeds.SearchSeriesFeed(), name='searchseries'),
    re_path(r'^search/series/(?P<searchtype>[bmae])/(?P<searchterms>.+)/$', feeds.SearchSeriesFeed(), name='searchseries'),

    re_path(r'^search/(?P<searchterms>.+)/$', feeds.SearchTypesFeed(), name='searchtypes'),

    re_path(r'^convert/(?P<book_id>[0-9]+)/(?P<convert_type>.+)/$', dl.ConvertFB2, name='convert'),
    re_path(r'^download/(?P<book_id>[0-9]+)/(?P<zip_flag>[0-1])/$', dl.Download, name='download'),
    re_path(r'^cover/(?P<book_id>[0-9]+)/$', dl.Cover, name='cover'),
    re_path(r'^thumb/(?P<book_id>[0-9]+)/$', dl.Thumbnail, name='thumb'),
    path('thumb/', dl.Cover, name='covertmpl'),

    path('', feeds.MainFeed(), name='main'),
]

sopds/urls.py
from django.contrib import admin
from django.urls import path, include, reverse_lazy
from django.views.generic import RedirectView

# from django.contrib.auth import logout

urlpatterns = [
    path('opds/', include('opds_catalog.urls', namespace='opds')),
    path('web/', include('sopds_web_backend.urls', namespace='web')),
    path('admin/', admin.site.urls),
    #path('logout/', logout, {'next_page':'/web/'}, name='logout'),   
    #path('', include('sopds_web_backend.urls', namespace='web', app_name='opds_web_backend')),
    path('', RedirectView.as_view(url=reverse_lazy("web:main"))),
]

sopds_web_backend/urls.py
from django.urls import re_path, path
from sopds_web_backend import views

app_name = 'opds_web_backend'

urlpatterns = [
    re_path(r'^search/books/$', views.SearchBooksView, name='searchbooks'),
    re_path(r'^search/authors/$', views.SearchAuthorsView, name='searchauthors'),
    re_path(r'^search/series/$', views.SearchSeriesView, name='searchseries'),
    path('catalog/', views.CatalogsView, name='catalog'),
    path('book/', views.BooksView, name='book'),
    path('author/', views.AuthorsView, name='author'),
    path('genre/', views.GenresView, name='genre'),
    path('series/', views.SeriesView, name='series'),
    path('login/', views.LoginView, name='login'),
    path('logout/', views.LogoutView, name='logout'),
    path('bs/delete/', views.BSDelView, name='bsdel'),
    path('bs/clear/', views.BSClearView, name='bsclear'),
    path('', views.hello, name='main'),
]

# handler403 = 'views.handler403'

sopds_web_backend/models.py
from django.db import models

# Create your models here.

sopds_web_backend/views.py
from random import randint

from django.shortcuts import render, redirect
from django.template.context_processors import csrf
from django.db.models import Count, Min
from django.utils.translation import gettext as _
from django.contrib.auth import authenticate, login, logout, REDIRECT_FIELD_NAME
from django.contrib.auth.decorators import user_passes_test
from django.views.decorators.vary import vary_on_headers
from django.urls import reverse, reverse_lazy
from django.utils.html import strip_tags
from django.db.models import Q
from django.http import HttpResponseForbidden

from opds_catalog import models
from opds_catalog.models import Book, Author, Series, bookshelf, Counter, Catalog, Genre, lang_menu
from opds_catalog import settings
from constance import config
from opds_catalog.opds_paginator import Paginator as OPDS_Paginator


from sopds_web_backend.settings import HALF_PAGES_LINKS

def sopds_login(function=None, redirect_field_name=REDIRECT_FIELD_NAME, url=None):
    actual_decorator = user_passes_test(
        lambda u: (u.is_authenticated if config.SOPDS_AUTH else True),
        login_url=reverse_lazy(url),
        redirect_field_name=redirect_field_name
    ) 
    if function:
        return actual_decorator(function)
    return actual_decorator

def sopds_processor(request):
    args={}
    args['app_title']=settings.TITLE
    args['sopds_auth']=config.SOPDS_AUTH
    args['sopds_version']=settings.VERSION
    args['alphabet'] = config.SOPDS_ALPHABET_MENU
    args['splititems'] = config.SOPDS_SPLITITEMS
    args['fb2tomobi'] = (config.SOPDS_FB2TOMOBI!="")
    args['fb2toepub'] = (config.SOPDS_FB2TOEPUB!="")
    args['nozip'] = settings.NOZIP_FORMATS
    args['cache_t']=0

    if config.SOPDS_ALPHABET_MENU:
        args['lang_menu'] = lang_menu
    
    if config.SOPDS_AUTH:
        user=request.user
        if user.is_authenticated:
            result=[]
            for row in bookshelf.objects.filter(user=user).order_by('-readtime')[:8]:
                book = Book.objects.get(id=row.book_id)
                p = {'id':row.id, 'readtime': row.readtime, 'book_id': row.book_id, 'title': book.title, 'authors':book.authors.values()}
                result.append(p)
            args['bookshelf']=result
        
    books_count = Counter.objects.get_counter(models.counter_allbooks)
    if books_count:
        random_id = randint(1,books_count)
        try:
            random_book = Book.objects.all()[random_id-1:random_id][0]
        except Book.DoesNotExist:
            random_book= None
    else:
        random_book= None        
                   
    args['random_book'] = random_book
    stats = { d['name']:d['value'] for d in Counter.obj.all().values() }
    stats['lastscan_date']=Counter.objects.get_lastscan()
    args['stats'] = stats
  
    return args

# Create your views here.
@vary_on_headers("HTTP_ACCEPT_LANGUAGE")
@sopds_login(url='web:login')
def SearchBooksView(request):
    #Read searchtype, searchterms, searchterms0, page from form
    args = {}
    args.update(csrf(request))

    if request.GET:
        searchtype = request.GET.get('searchtype', 'm')
        searchterms = request.GET.get('searchterms', '')
        #searchterms0 = int(request.POST.get('searchterms0', ''))
        page_num = int(request.GET.get('page', '1'))
        page_num = page_num if page_num>0 else 1
        
        #if (len(searchterms)<3) and (searchtype in ('m', 'b', 'e')):
        #    args['errormsg'] = 'Too few symbols in search string !';
        #    return render_to_response('sopds_error.html', args)
        
        if searchtype == 'm':
            #books = Book.objects.extra(where=["upper(title) like %s"], params=["%%%s%%"%searchterms.upper()]).order_by('title','-docdate')
            books = Book.objects.filter(search_title__contains=searchterms.upper()).order_by('search_title','-docdate')
            args['breadcrumbs'] = [_('Books'),_('Search by title'),searchterms]
            args['searchobject'] = 'title'
            
        if searchtype == 'b':
            #books = Book.objects.extra(where=["upper(title) like %s"], params=["%s%%"%searchterms.upper()]).order_by('title','-docdate')
            books = Book.objects.filter(search_title__startswith=searchterms.upper()).order_by('search_title','-docdate')
            args['breadcrumbs'] = [_('Books'),_('Search by title'),searchterms]   
            args['searchobject'] = 'title'         
            
        elif searchtype == 'a':
            try:
                author_id = int(searchterms)
                author = Author.objects.get(id=author_id)
                #aname = "%s %s"%(author.last_name,author.first_name)
                aname = author.full_name
            except:
                author_id = 0
                aname = ""                  
            books = Book.objects.filter(authors=author_id).order_by('search_title','-docdate')  
            args['breadcrumbs'] = [_('Books'),_('Search by author'),aname]   
            args['searchobject'] = 'author' 
            
        # Поиск книг по серии
        elif searchtype == 's':
            try:
                ser_id = int(searchterms)
                ser = Series.objects.get(id=ser_id).ser
            except:
                ser_id = 0
                ser = ""
            #books = Book.objects.filter(series=ser_id).order_by('search_title','-docdate')
            books = Book.objects.filter(series=ser_id).order_by('bseries__ser_no','search_title','-docdate')
            args['breadcrumbs'] = [_('Books'),_('Search by series'),ser]
            args['searchobject'] = 'series'
            
        # Поиск книг по жанру
        elif searchtype == 'g':
            try:
                genre_id = int(searchterms)
                section = Genre.objects.get(id=genre_id).section
                subsection = Genre.objects.get(id=genre_id).subsection
                args['breadcrumbs'] = [_('Books'),_('Search by genre'),section,subsection]
            except:
                genre_id = 0
                args['breadcrumbs'] = [_('Books'),_('Search by genre')]
                
            books = Book.objects.filter(genres=genre_id).order_by('search_title','-docdate') 
            args['searchobject'] = 'genre'
                                   
        # Поиск книг на книжной полке            
        elif searchtype == 'u':
            if config.SOPDS_AUTH:
                books = Book.objects.filter(bookshelf__user=request.user).order_by('-bookshelf__readtime')
                args['breadcrumbs'] = [_('Books'),_('Bookshelf'),request.user.username]
                #books = bookshelf.objects.filter(user=request.user).select_related('book')              
            else:
                books=Book.objects.filter(id=0)     
                args['breadcrumbs'] = [_('Books'), _('Bookshelf')] 
            args['searchobject'] = 'title'
            args['isbookshelf'] = 1
                
        # Поиск дубликатов для книги            
        elif searchtype == 'd':
            #try:
            book_id = int(searchterms)
            mbook = Book.objects.get(id=book_id)
            books = Book.objects.filter(title=mbook.title, authors__in=mbook.authors.all()).exclude(id=book_id).distinct().order_by('-docdate')
            args['breadcrumbs'] = [_('Books'),_('Doubles for book'),mbook.title]
            args['searchobject'] = 'title'
            
        # Поиск книги по ID. Хотел найти еще и дубликаты к книге, но почему-то не работает запрос правильно. Ума не приложу почему.    
        elif searchtype == 'i':
            try:
                book_id = int(searchterms)
                #mbook = Book.objects.get(id=book_id)
            except:
                book_id = 0
                #mbook = None
            books = Book.objects.filter(id=book_id) 
            args['breadcrumbs'] = [_('Books'),books[0].title]
            #books = Book.objects.filter(title=mbook.title, authors__in=mbook.authors.all()).distinct().order_by('-docdate')                
            #args['breadcrumbs'] = [_('Books'),mbook.title]
            args['searchobject'] = 'title'
        
        # prefetch_related on sqlite on items >999 therow error "too many SQL variables"    
        #if len(books)>0:
        #    books = books.select_related('authors','genres','series')

        # Добавляем Left Join с таблицей BookShelfб чтобы вытащить дату прочтения книги из книжной полки
        #books = books.filter(Q(bookshelf__isnull=True)|Q(bookshelf__user=request.user))
        #books = books.prefetch_related('bookshelf_set')
        #print(books.query)

        
        # Фильтруем дубликаты и формируем выдачу затребованной страницы
        books_count = books.count()
        op = OPDS_Paginator(books_count, 0, page_num, config.SOPDS_MAXITEMS, HALF_PAGES_LINKS)
        items = []
        
        prev_title = ''
        prev_authors_set = set()
        
        # Начаинам анализ с последнего элемента на предидущей странице, чторбы он "вытянул" с этой страницы
        # свои дубликаты если они есть
        summary_DOUBLES_HIDE =  config.SOPDS_DOUBLES_HIDE and (searchtype != 'd')
        start = op.d1_first_pos if ((op.d1_first_pos==0) or (not summary_DOUBLES_HIDE)) else op.d1_first_pos-1
        finish = op.d1_last_pos
        
        for row in books[start:finish+1]:
            p = {'doubles':0, 'lang_code': row.lang_code, 'filename': row.filename, 'path': row.path, \
                  'registerdate': row.registerdate, 'id': row.id, 'annotation': strip_tags(row.annotation), \
                  'docdate': row.docdate, 'format': row.format, 'title': row.title, 'filesize': row.filesize//1000,\
                  'authors': row.authors.values(), 'genres': row.genres.values(), 'series': row.series.values(),'ser_no': row.bseries_set.values('ser_no'),\
                  'readtime':row.bookshelf_set.filter(user=request.user).values('readtime') if config.SOPDS_AUTH else None
                 }
            if summary_DOUBLES_HIDE:

sopds_web_backend/templates/sopds_authors.html
{% extends "sopds_main.html" %}
{% load i18n %}

{% block body %}
<table>
{%  for a in authors %}
	<tr><td>
		<a href="{% url "web:searchbooks" %}?searchtype=a&searchterms={{a.id}}"><b>{{ a.full_name }}</b></a> <span style="font-size:80%;">{% blocktrans with a_book_count=a.book_count %}Total: {{ a_book_count }} books.{% endblocktrans %}</span>
	</td></tr>		
{% endfor %}
</table>

{% if paginator.num_pages > 1 %}
<ul class="pagination" role="navigation" aria-label="Pagination">
  <li class="pagination-previous {% if not paginator.has_previous %}disabled{%endif%}">
      {% if paginator.has_previous %}<a href="{% url "web:searchauthors" %}?searchtype={{searchtype}}&searchterms={{searchterms}}&page={{paginator.previous_page_number}}" aria-label="Previous page"> {%endif%}
         {% trans "Previous page" %}
      {% if paginator.has_previous %}</a>{%endif%}
  </li>
  
  {% for pn in paginator.page_range %}
     {% if paginator.number == pn %}
        <li class="current">{{pn}}</li>
     {% else %}
        <li><a href="{% url "web:searchauthors" %}?searchtype={{searchtype}}&searchterms={{searchterms}}&page={{pn}}" aria-label="Page {{pn}}">{{pn}}</a></li>
     {% endif %}   
        {# <li class="ellipsis" aria-hidden="true"></li> #}
  {% endfor %}
  
  <li class="pagination-next" {% if not paginator.has_next %}disabled{%endif%}>
      {% if paginator.has_next %}<a href="{% url "web:searchauthors" %}?searchtype={{searchtype}}&searchterms={{searchterms}}&page={{paginator.next_page_number}}" aria-label="Next page">{%endif%}
         {% trans "Next page" %}
      {% if paginator.has_next %}</a>{%endif%}
  </li>
</ul>
{% else %}
<div class="large-12 column"><p></p></div>
{% endif %}

{% endblock %}  {# body #}

sopds_web_backend/templates/sopds_books.html
{% extends "sopds_main.html" %}
{% load i18n %}

{% block body %}
<script>
       function del_bsbook(b_id, b_t) {
           $('#DeleteBook_btnYes').attr("href","{% url "web:bsdel" %}?book="+b_id);
           $('#DeleteBook_image').attr("src","{% url "opds:covertmpl" %}"+b_id+"/");
           $('#DeleteBook_title').text(b_t);
           $('#DeleteBookModal').foundation('open');
       }
</script>
           
<div id="DeleteBookModal" class="reveal tiny text-center" data-reveal>
  <h5 id="DeleteBookModalTitle">{% trans "Confirm the deletion of the book to your bookshelf." %}</h5>
  <table><tr>	
  <td width="100px" style="padding:0rem 0rem;">
      <img src="" id="DeleteBook_image" style="max-height: 100px; max-width: 100px">
  </td> 
  <td style="font-size:100%; padding:3px">
      <p id="DeleteBook_title"></p>
  </td>
  </tr>
  </table>
  <p class="text-center"><a href="#" class="secondary button" id="DeleteBook_btnYes">{% trans "Delete" %}</a>
                         &nbsp;&nbsp;&nbsp;<a class="close button" data-close>{% trans "Cancel" %}</a></p>
  <button class="close-button" data-close aria-label="Close modal" type="button">
    <span aria-hidden="true">&times;</span>
  </button>
</div>

 {% if isbookshelf %}
 <div id="ConfirmModal" class="reveal tiny text-center" data-reveal>
  <h5 id="ConfirmModalTitle">{% trans "Confirm to clear your bookshelf." %}</h5>
  <p></p>
  <p class="text-center"><a href="{% url "web:bsclear" %}" class="secondary button" id="Confirm_btnYes">{% trans "Clear" %}</a>
                         &nbsp;&nbsp;&nbsp;<a class="close button" data-close>{% trans "Cancel" %}</a></p>
  <button class="close-button" data-close aria-label="Close modal" type="button">
    <span aria-hidden="true">&times;</span>
  </button>
</div>

 <a class="alert button small" data-open="ConfirmModal">{%  trans "Clear bookshelf" %}</a>
 {% endif %}

{%  for b in books %}
		<div class="large-12 column">
			<b>{{ b.title }}</b>
			<i style="font-size:80%;">{% trans "Download:" %} </i>
			<i><a href="{% url 'opds_catalog:download' b.id 0 %}"><span class="label small">{{b.format}}</span></a></i>&nbsp;
            {% if not b.format in nozip %}
                <i><a href="{% url 'opds_catalog:download' b.id 1 %}"><span class="label small">{{b.format}}+zip</span></a></i>&nbsp;
            {%  endif %}
			{% if b.format == 'fb2' and fb2toepub %}
			   <i><a href="{% url 'opds_catalog:convert' b.id 'epub' %}"><span class="label small">epub</span></a></i>&nbsp;
			{% endif %}
			{% if b.format == 'fb2' and fb2tomobi %}
			   <i><a href="{% url 'opds_catalog:convert' b.id 'mobi' %}"><span class="label small">mobi</span></a></i>&nbsp;
			{% endif %}			
			{% if isbookshelf %}
			&nbsp;&nbsp;<i><a href="#" onclick="del_bsbook({{ b.id }},'{{b.title}}');"><span class="secondary label small">&nbsp;{% trans "Delete from bookshelf" %}&nbsp;</span></a></i>
		    {% endif %}
		</div>
		
		<div class="large-12 column">
		    <table><tr>	
		    <td width="100px" style="padding:0rem 0rem;">
			     <img src="{% url 'opds_catalog:thumb' b.id %}" type="image/jpeg" width="80px">
			</td>
			<td style="font-size:80%; padding:1rem 1rem;">
				<b>{% trans "Book title:" %}</b> {{ b.title }} <br>
				{% if b.authors.count > 0 %}
				   <b>{% trans "Authors:" %}</b>{% for a in b.authors %} <a href="{% url "web:searchbooks" %}?searchtype=a&searchterms={{a.id}}">{{a.full_name}}</a>{% if not forloop.last %},{%endif%} {%endfor%}<br>
				{% endif %}
				{% if b.genres.count > 0 %}
				   <b>{% trans "Genres:" %}</b>{% for g in b.genres %} <a href="{% url "web:searchbooks" %}?searchtype=g&searchterms={{g.id}}">{{g.subsection}}</a>{% if not forloop.last %},{%endif%} {%endfor%} <br>
				{% endif %}
				{% if b.series.count > 0 %}
				   <b>{% trans "Series:" %}</b> {% for s in b.series %} <a href="{% url "web:searchbooks" %}?searchtype=s&searchterms={{s.id}}">{{s.ser}}</a>{% if not forloop.last %},{%endif%} {%endfor%} <br>
                   <b>{% trans "No in Series:" %}</b> {% for s in b.ser_no %}{{s.ser_no}}{% if not forloop.last %},{%endif%} {%endfor%} <br>
				{% endif %}
				<b>{% trans "File:" %}</b> {{ b.path }}/{{ b.filename }} <br>
				<b>{% trans "File size:" %}</b> {{ b.filesize }}Кб.<br>
				<b>{% trans "Changes date:" %}</b> {{ b.docdate }} <br>	
				{% if b.doubles > 0 %}
				<b>{% trans "Doubles for book:" %}</b> <a href="{% url "web:searchbooks" %}?searchtype=d&searchterms={{b.id}}">{{ b.title }} ({{b.doubles}}шт.)</a><br>
				{% endif %}
				{% if b.readtime %}
                    <b>{% trans "Read date:" %}</b> <span class="label small">{{ b.readtime.0.readtime }}</span><br>
				{% endif %}

			</td>
			</tr>
			<tr>
			<td colspan="2">
			    <p style="font-size:80%;">{{ b.annotation }}</p>
			</td>
			</tr></table>
		</div>			
{% endfor %}

{% if paginator.num_pages > 1 %}
<ul class="pagination" role="navigation" aria-label="Pagination">
  <li class="pagination-previous {% if not paginator.has_previous %}disabled{%endif%}">
      {% if paginator.has_previous %}<a href="{% url "web:searchbooks" %}?searchtype={{searchtype}}&searchterms={{searchterms}}&page={{paginator.previous_page_number}}" aria-label="Previous page"> {%endif%}
         {% trans "Previous page" %}
      {% if paginator.has_previous %}</a>{%endif%}
  </li>
  
  {% for pn in paginator.page_range %}
     {% if paginator.number == pn %}
        <li class="current">{{pn}}</li>
     {% else %}
        <li><a href="{% url "web:searchbooks" %}?searchtype={{searchtype}}&searchterms={{searchterms}}&page={{pn}}" aria-label="Page {{pn}}">{{pn}}</a></li>
     {% endif %}   
        {# <li class="ellipsis" aria-hidden="true"></li> #}
  {% endfor %}
  
  <li class="pagination-next" {% if not paginator.has_next %}disabled{%endif%}>
      {% if paginator.has_next %}<a href="{% url "web:searchbooks" %}?searchtype={{searchtype}}&searchterms={{searchterms}}&page={{paginator.next_page_number}}" aria-label="Next page">{%endif%}
         {% trans "Next page" %}
      {% if paginator.has_next %}</a>{%endif%}
  </li>
</ul>
{% endif %}

{% endblock %}  {# body #}

sopds_web_backend/templates/sopds_menu.html
{% load i18n %}

{% if not alphabet %}
	<div id="main_menu">
	  <ul class="menu sopdsmenu" style="font-size:100%;"> {# vertical medium-horizontal menu #}
	    <li {% if current == "catalog" %} class="active" {% endif %}><a href="{% url "web:catalog" %}">{% trans "Catalogs" %}</a></li>
	    <li {% if current == "book" %} class="active" {% endif %}><a href="{% url "web:book" %}?lang=0">{% trans "Books" %}</a></li>
	    <li {% if current == "author" %} class="active" {% endif %}><a href="{% url "web:author" %}?lang=0">{% trans "Authors" %}</a></li>
	    <li {% if current == "genre" %} class="active" {% endif %}><a href="{% url "web:genre" %}">{% trans "Genres" %}</a></li>
	    <li {% if current == "series" %} class="active" {% endif %}><a href="{% url "web:series" %}?lang=0">{% trans "Series" %}</a></li>
	  </ul>
	</div>
{% else %}
	<div id="main_menu">
	  <ul class="dropdown menu sopdsmenu" style="font-size:100%;" data-dropdown-menu data-close-on-click-inside="false">
	    <li {% if current == "catalog" %} class="active" {% endif %}><a href="{% url "web:catalog" %}">{% trans "Catalogs" %}</a></li>
	    <li {% if current == "book" %}class="active"{% endif %} ><a href="#">{% trans "Books" %}</a>
	        <ul class="menu sopdsmenu">
	        {% for key, value in lang_menu.items %}
	            <li><a href="{% url "web:book" %}?lang={{ key }}">{{ value }}</a></li>
	        {% endfor %}    
	        </ul>
	    </li>
	    <li {% if current == "author" %} class="active" {% endif %}><a href="#">{% trans "Authors" %}</a>	    
	        <ul class="menu sopdsmenu">
	        {% for key, value in lang_menu.items %}
	            <li><a href="{% url "web:author" %}?lang={{ key }}">{{ value }}</a></li>
	        {% endfor %}  
	        </ul>	    
	    </li>
	    <li {% if current == "genre" %} class="active" {% endif %}><a href="{% url "web:genre" %}">{% trans "Genres" %}</a>    
	    </li>
	    <li {% if current == "series" %} class="active" {% endif %}><a href="#">{% trans "Series" %}</a>
	        <ul class="menu sopdsmenu">
	        {% for key, value in lang_menu.items %}
	            <li><a href="{% url "web:series" %}?lang={{ key }}">{{ value }}</a></li>
	        {% endfor %}  
	        </ul>	    
	    </li>
	  </ul>
	</div>
{% endif %}